### ISSUE TITLE
app stopped when upload or taking a photo

### ISSUE THREAD

**Issue by kr-nahid** [BoomApps-LLC/SteemApp-Android#1] opened 2018-06-29 09:04 UTC
#### Expected behavior
user should be able to upload photo with taking photo or gallery photos without crash. 

#### Actual behavior
when i try to upload a photo by taking photo it loading and crash and same condition when i try to upload photos from gallery it occurs to crash .

#### How to reproduce
* download the app [here ](https://play.google.com/store/apps/details?id=com.boomapps.steemapp)
* open the app with your steemit id and posting key
* now scroll on create post
* then try to upload a photo by taking camera or from gellery
* note the bug

> Browser/App version: SteemApp v1.0.3
 Operating system: Android **7.1.2** N2G47H

#### Recording Of The Bug
https://www.youtube.com/watch?v=X5bMZecyERk

**Comment by tobias-g1** [comment] 2018-07-01 10:12
Duplicate of #8 and likely #3, I have attached a log-cat to #8 as that's where I replicated it.

**Comment by brazer** [comment] 2018-07-22 07:17
It was fixed. See #3.

**Closed by brazer** 2018-07-22 07:17 UTC
