### ISSUE TITLE
Application stops while uploading photos

### ISSUE THREAD

**Issue by rezamusic881** [BoomApps-LLC/SteemApp-Android#21] opened 2018-07-03 15:40 UTC
#### <center>Expected behavior</center>
Supposedly, The app does not crash when uploading photos via the "Take a Photo & Choose from Library" feature

#### <center>Actual behavior</center>
The app is stuck when uploading photos via the "Fetch Photos & Select from Library" feature. I tried to produce with another device (Android 6.0) but the same thing happened.

#### <center>How to reproduce</center>
Do login first, access the Create Post feature and Click on Upload feature image on the bottom or on (icon image), then the application will crash.

#### <center>Record of the issues</center>
https://youtu.be/CfuQzduEzNk

#### <center>Logcat</center>
```07-03 22:10:08.183  5626  6107 E         : Image upload exception
07-03 22:10:08.183  5626  6107 E         : com.google.api.client.http.HttpResponseException: 500 Internal Server Error
07-03 22:10:08.183  5626  6107 E         : {"error":{"name":"internal_error"}}
07-03 22:10:08.183  5626  6107 E         : 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
07-03 22:10:08.183  5626  6107 E         : 	at eu.bittrade.libs.steemj.image.upload.SteemJImageUpload.executeMultipartRequest(SteemJImageUpload.java:171)
07-03 22:10:08.183  5626  6107 E         : 	at eu.bittrade.libs.steemj.image.upload.SteemJImageUpload.uploadImage(SteemJImageUpload.java:128)
07-03 22:10:08.183  5626  6107 E         : 	at com.boomapps.steemapp.repository.SteemWorker.uploadImage(SteemWorker.kt:203)
07-03 22:10:08.183  5626  6107 E         : 	at com.boomapps.steemapp.repository.network.NetworkRepositoryDefault$uploadNewPhoto$1.call(NetworkRepositoryDefault.kt:94)
07-03 22:10:08.183  5626  6107 E         : 	at com.boomapps.steemapp.repository.network.NetworkRepositoryDefault$uploadNewPhoto$1.call(NetworkRepositoryDefault.kt:29)
07-03 22:10:08.183  5626  6107 E         : 	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
07-03 22:10:08.183  5626  6107 E         : 	at io.reactivex.Observable.subscribe(Observable.java:10955)
07-03 22:10:08.183  5626  6107 E         : 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
07-03 22:10:08.183  5626  6107 E         : 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
07-03 22:10:08.183  5626  6107 E         : 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-03 22:10:08.183  5626  6107 E         : 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-03 22:10:08.183  5626  6107 E         : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-03 22:10:08.183  5626  6107 E         : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-03 22:10:08.183  5626  6107 E         : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-03 22:10:08.183  5626  6107 E         : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-03 22:10:08.183  5626  6107 E         : 	at java.lang.Thread.run(Thread.java:760)

**Comment by tobias-g1** [comment] 2018-07-03 17:20
Duplicate of #8, #1

**Comment by BoomAppsLLC** [comment] 2018-07-04 10:52
Thank you for bug reporting. Thanks, @tobias-g1 , for comment.

**Closed by BoomAppsLLC** 2018-07-04 10:52 UTC
