### ISSUE TITLE
Steemapp V2. 0.3; Incorrect date and time of post. All post showing 1 month ago 

### ISSUE THREAD

**Issue by djavalord** [BoomApps-LLC/SteemApp-Android#18] opened 2018-07-01 23:04 UTC
#### Expected behavior
I expect that when I log in to the app, I should be able to see the correct date a blog is posted.  Either in hours or days 

#### Actual behavior
When I open my blog to see posts,  I noticed that all my post are showing wrong date of post.  Post that were made few days ago shows 1 month ago. Same thing in trending post, Feed and New post. 

#### How to reproduce
* download the app [here](https://play.google.com/store/apps/details?id=com.boomapps.steemapp)
* sign in to the app using the required details 
*  on your blog page, check the date if the post that is just under your username 
* the date displays 1 month ago instead of the actual time of the post. 
* sweep right to go to feed
* check the date of post under the username 
* it still read or display 1 month ago 
* sweep right to go to  New
* check the date of post under the username 
* it still read or display 1 month ago 
* scroll down to see that all the posts will show 1 month ago 
* thus the bug 

---
* Browser/App version: steemapp version 2.0.3
* Operating system: android  8.0 Oreo.  Tecno camon X

#### Recording Of The Bug
https://youtu.be/PbXYD4KRowE

#### GitHub Account
https://github.com/djavalord

**Comment by tobias-g1** [comment] 2018-07-02 17:50
Duplicate of #10 #11, Resolved in #12

**Comment by brazer** [comment] 2018-07-04 11:29
Thank you, guys, for comments.

**Closed by brazer** 2018-07-04 11:29 UTC
